sudo: required
language: node_js
node_js:
- '4'
services:
- docker
script:
- bash build_npm.sh
deploy:
  provider: npm
  skip_cleanup: true
  email: ellery-newcomer@utulsa.edu
  on:
    tags: true
  api_key:
    secure: nNi3keWcuiVuLZ8UpWluPjd6Oa7j8dsAZTkI3Wz/3olLrCFoYAVUJgI8ZKqzvE2K+wok1SZkI03zOaxpSKc9PXg808ZKJD3y1XJDOAUzlpxE1dT8NPdlLe4S/4miynR/HmRRw2kMm/d0B2JUdCVkARk6UeusN3IrHZhXwOON+h/FdSX53nYGp4y6HagKpqbnvgXZAzHUwMb5HV7KHUjxUy9S89k4UoY2WaEIruqU9mo3c2p0O2V4Epv3W5Ek167i9/ivoU0VjxP13rWjKLfyivSGekXw2gRHg6SLHrZkRqfe2M9vx2MyOSF6qaBT+hyKesYE+EVOEhoTTPhB+HxuC7rp6ZT3pBxFZrqbG8PteoCwgRt4yhK8rJCY4xOTzDiJ/0YYXg7CE0KJ3NL7Aa90wtCbQuXFvQc2wQOrnO1OM7UunMHs/MpE8kWOEwdAvzZ3ZWIPg1mRNjilfINRf8bJmcYMT6SFwZ8b5IezCRdWe8LW4xqJMUnJG9RH7qINKfG49ZfmrRL5Y7nC6RgN+6eF9++FPIzugjoy/fx9diwx4EIfRRHChBprcNsqbeyRewUNBEFclzZsZv2M5rVauznObe2dZ/o7Z30tXvQO+Jy5xEIQUL1cO0h1+UUAzf9whk72RIorL0aqb93B1nV3lJaRAqidpn7LKlfweBQXyl2BRAo=
